//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MappingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetVehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetVehicle()
        {
            this.AspNetDriver_Vehicle = new HashSet<AspNetDriver_Vehicle>();
            this.AspNetVehicleLocationTables = new HashSet<AspNetVehicleLocationTable>();
        }
    
        public int Id { get; set; }
        public string VehicleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetDriver_Vehicle> AspNetDriver_Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetVehicleLocationTable> AspNetVehicleLocationTables { get; set; }
    }
}
