//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MappingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetVehicleLocationTable
    {
        public int Id { get; set; }
        public Nullable<double> LastLatitude { get; set; }
        public Nullable<double> LastLongitude { get; set; }
        public string EngineRPM { get; set; }
        public string Speed { get; set; }
        public string FuelPressure { get; set; }
        public string Throttle_Pos { get; set; }
        public string FuelType { get; set; }
        public string Fuel_Rail_Pressure { get; set; }
        public Nullable<int> TimeStamp { get; set; }
        public int VehicleID { get; set; }
        public Nullable<double> Altitude { get; set; }
    
        public virtual AspNetVehicle AspNetVehicle { get; set; }
    }
}
