//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MappingProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MappingDatabaseEntities : DbContext
    {
        public MappingDatabaseEntities()
            : base("name=MappingDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetAdmin_Managers> AspNetAdmin_Managers { get; set; }
        public virtual DbSet<AspNetDriver_Vehicle> AspNetDriver_Vehicle { get; set; }
        public virtual DbSet<AspNetManager_Drivers> AspNetManager_Drivers { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspNetVehicle> AspNetVehicles { get; set; }
        public virtual DbSet<AspNetVehicleLocationTable> AspNetVehicleLocationTables { get; set; }
    }
}
